fixing logical race when Close is called before Invoke
smartcontractkit/wsrpc pull request #50
Opened 2023-12-08 00:43 UTC by patrickhuie19

This is intended as a hotfix for an observed logical race (MERC-2753). 

I've added a tag/branch v0.7.3 for the patch to 0.7.2.

2023-12-08 01:32 UTC, samsondav submitted a review, later dismissed

2023-12-08 13:56 UTC, samsondav submitted a review, later dismissed

2023-12-08 14:21 UTC, samsondav approved these changes

2023-12-08 14:21 UTC, samsondav requested changes

2023-12-08 14:21 UTC, samsondav commented on client.go
> +	}
```suggestion
	cc.mu.RLock()
	if cc.addrConn == nil {
	        cc.mu.RUnlock()
		// Close() has been called
		return errors.New("client Close() called")
	}
```

2023-12-10 15:12 UTC, jmank88 commented on go.mod
> +replace golang.org/x/net => golang.org/x/net v0.19.0
These replaces have no effect since the deps are not used.

2023-12-10 15:15 UTC, jmank88 commented on client.go
Since `cc.mu.RUnlock()` is released on 382, isn't is possible for `Close` to be called after 382 and before 414, where `cc.addrConn` is accessed again?

2023-12-11 20:37 UTC, patrickhuie19 commented on client.go
Yes, that's possible - thanks for the catch!

 If we go with the current approach, I'd add a similar nil check for `cc.addrConn` after the `cc.mu.RLock()` call in line 412.
 
 I'm wondering if there's a cleaner way to let Invoke know that Close has been called, but a nil check (while indirect) seems as clean as listening for a channel or checking the status of a boolean flag.

2023-12-11 21:55 UTC, patrickhuie19 commented on go.mod
> +replace golang.org/x/net => golang.org/x/net v0.19.0
Thanks - should `go mod tidy` catch that? Or is there another idiomatic/preferred tool to catch unused deps?

2023-12-11 21:57 UTC, jmank88 commented on go.mod
> +replace golang.org/x/net => golang.org/x/net v0.19.0
I don't know why it doesn't auto-remove - maybe some risk :shrug: 
I am not aware of any tools, but I was thinking of writing one for formatting and it could include this sort of thing too.

2023-12-12 14:35 UTC, jmank88 approved these changes

2023-12-13 16:12 UTC, merged