[DRAFT] feat: rename lint workflow, apply reusable action
smartcontractkit/wsrpc pull request #53
Opened 2024-01-17 22:29 UTC by erikburt

**Note**: This PR is based on #51 - will rebase once that is merged.

This adds a release process for this repo managed by [changesets](https://github.com/changesets/changesets).

2024-01-17 22:41 UTC, chainchad commented on .github/workflows/cd-release.yml
> +name: CI Lint
```suggestion
name: CD Release
```

2024-01-17 22:41 UTC, chainchad commented on .github/workflows/cd-release.yml
> +          # aws inputs - TODO: setup gati
Do we plan to setup GATI before merging?

2024-01-17 22:41 UTC, chainchad commented on .github/workflows/dependency-check.yml
> +            go-version-file: 'go.mod'
The previous indentation level looks more correct than this?

2024-01-17 22:41 UTC, chainchad commented on .github/workflows/dependency-check.yml
> +        uses: smartcontractkit/push-gha-metrics-action@v2.0.2
You'll want to change the `with.this-job-name` input on this step to match the job name `ci-test`.

2024-01-17 22:41 UTC, chainchad commented on README.md
❤️

2024-01-17 23:09 UTC, erikburt commented on .github/workflows/cd-release.yml
> +          # aws inputs - TODO: setup gati
Yes - waiting on https://github.com/smartcontractkit/infra/pull/5520 to be applied/merged.

2024-01-17 23:11 UTC, erikburt commented on .github/workflows/dependency-check.yml
> +        uses: smartcontractkit/push-gha-metrics-action@v2.0.2
This job's name is `Go` - https://github.com/smartcontractkit/wsrpc/blob/8182329429eef516b92805d5da9670ac7da00389/.github/workflows/dependency-check.yml#L24

2024-01-22 21:08 UTC, patrickhuie19 approved these changes

2024-01-23 14:58 UTC, patrickhuie19 requested changes

2024-01-23 14:58 UTC, patrickhuie19 commented on package.json
> +  "name": "wsrpc",
Should this have the `@chainlink/` prefix for safe publishing?

2024-01-23 17:50 UTC, erikburt commented on package.json
> +  "name": "wsrpc",
I don't think it's necessary but it can't hurt.

The [`private: true`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#private) lower in the `package.json` ensures that this won't get published to npm.

2024-01-23 17:55 UTC, erikburt commented on package.json
> +  "name": "wsrpc",
Added in e3a0fdb89f37ca5888f0a4e07a6d6de876b562c8

2024-01-23 20:35 UTC, merged